# Generated by Django 3.2.8 on 2021-10-16 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fields',
            old_name='mun',
            new_name='mun_name',
        ),
        migrations.RemoveField(
            model_name='seasons',
            name='description',
        ),
        migrations.AddField(
            model_name='fields',
            name='culture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.cultures'),
        ),
        migrations.AddField(
            model_name='fields',
            name='state',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fields',
            name='yield_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Yields',
        ),
    ]
